services:

  db:
    image: 'postgres:16'
    container_name: postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: fastapi
    restart: unless-stopped

    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    ports:
      - "80:80"

    depends_on:
      db:
        condition: service_healthy

    networks:
      - network

volumes:
  postgres_data:
    driver: local

networks:
  network:
    driver: bridge