"""initial

Revision ID: 22e7c97622f4
Revises: 
Create Date: 2026-09-06 16:00:24.078485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22e7c97622f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geopoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('geo_latitude', sa.Float(), nullable=True),
    sa.Column('geo_longitude', sa.Float(), nullable=True),
    sa.Column('geo_link', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Enum('VISITED', 'NOT_VISITED', name='geostatusenum'), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'DONE', name='tripstatusenum'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips')
    op.drop_table('geopoints')
    # ### end Alembic commands ###
