"""change geopoint geolink limits

Revision ID: 5c1c2a06470f
Revises: eac7e399f221
Create Date: 2026-09-08 10:59:08.721596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c1c2a06470f'
down_revision: Union[str, Sequence[str], None] = 'eac7e399f221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('geopoints', 'geo_link',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=3000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('geopoints', 'geo_link',
               existing_type=sa.String(length=3000),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###
