"""add date field to geopoints

Revision ID: d75d83881038
Revises: 22e7c97622f4
Create Date: 2026-09-06 16:46:21.788213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd75d83881038'
down_revision: Union[str, Sequence[str], None] = '22e7c97622f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geopoints', sa.Column('date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geopoints', 'date')
    # ### end Alembic commands ###
